#! /bin/sh
# ------------------------
# administrative reset of LDAP user account password
#
# 20160129 bear - version 1.0
#

PATH=/usr/bin:/bin:/usr/sbin:/sbin
SCRIPTNAME=$(basename $0)
SCRIPTPATH=$(dirname $0)

if [ -z "$1" ] ; then
	echo Usage: $SCRIPTNAME username
	exit 1
fi

. $SCRIPTPATH/ldap-util.shlib

uid=$1
ldap_obj_exists uid=$uid $LDAP_USER_OU || exit 1

new_pw=$(slappasswd -g)
crypt_pw=$(slappasswd -s $new_pw)

echo $SCRIPTNAME: new password for user $uid will be $new_pw

ldap_modify_connect uid=$uid $LDAP_USER_OU
ldap_set userPassword $crypt_pw ; echo -
ldap_set pwdReset TRUE ; echo
ldap_disconnect
