(DEFINEQ DIVP (LAMBDA (X LISZT)
  (PROG (Y)
    (SETQ Y (CAR LISZT))
    (COND ((# Y)
           (PROG (I Z)
             (SETQ Z (/ X Y))
             (SETQ I (INT Z))
             (COND ((EQ Z I) (RETURN T))
                   (T (DIVP X (CDR LISZT))))))
           (T NIL)))))

(DEFINEQ PRIMES (LAMBDA (N)
        (PROG (COUNT PRIMES)
            (SETQ COUNT 3)
            (SETQ PRIMES (LIST 2))
       NEXT (COND ((> N (LENGTH PRIMES))
                  (COND ((DIVP COUNT PRIMES) NIL)
                        (T (NCONC PRIMES (LIST COUNT)))))
            (T (RETURN PRIMES)))
        (SETQ COUNT (+ COUNT 1))
        (GO NEXT))))

