(defun divp (n list)
  (cond ((numberp (car list)) (cond ((zerop (mod n (car list))) T)
                                    ((divp n (cdr list)) T)))))

(defun primes (n)
  (prog (count primes)
    (setq count 3)
    (setq primes (list 2))
    NEXT (cond ((< (length primes) n)
                (cond ((divp count primes) nil)
                      (T (nconc primes (list count)))))
               (T (return primes)))
    (setq count (+ count 1))
    (go NEXT)))
